### ISSUE TITLE
微博推送报错

### ISSUE THREAD

**Issue by onlyzqy** [snowtafir/yuki-plugin#14]
[23:48:18.484][ERRO][yuki插件---微博动态推送定时任务(*/5 * * * *)] TypeError: Cannot read properties of null (reading 'join')
    at WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:144:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WeiboTask.pushDynamicMessages (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:111:29)
    at async WeiboTask.runTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:25:9)
    at async YukiWeibo.newPushTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/apps/weibo.js:60:9)
    at async Job.job (file:///mnt/Disk1/TRSS-Yunzai/lib/plugins/loader.js:516:9) {
  [stack]: "TypeError: Cannot read properties of null (reading 'join')\n" +
    '    at WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:144:63)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async WeiboTask.pushDynamicMessages (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:111:29)\n' +
    '    at async WeiboTask.runTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:25:9)\n' +
    '    at async YukiWeibo.newPushTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/apps/weibo.js:60:9)\n' +
    '    at async Job.job (file:///mnt/Disk1/TRSS-Yunzai/lib/plugins/loader.js:516:9)',
  [message]: "Cannot read properties of null (reading 'join')"
}

**Comment by snowtafir** [comment]
> [23:48:18.484][ERRO][yuki插件---微博动态推送定时任务(*/5 * * * *)] TypeError: Cannot read properties of null (reading 'join') at WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:144:63) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async WeiboTask.pushDynamicMessages (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:111:29) at async WeiboTask.runTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:25:9) at async YukiWeibo.newPushTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/apps/weibo.js:60:9) at async Job.job (file:///mnt/Disk1/TRSS-Yunzai/lib/plugins/loader.js:516:9) { [stack]: "TypeError: Cannot read properties of null (reading 'join')\n" + ' at WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:144:63)\n' + ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' + ' at async WeiboTask.pushDynamicMessages (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:111:29)\n' + ' at async WeiboTask.runTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:25:9)\n' + ' at async YukiWeibo.newPushTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/apps/weibo.js:60:9)\n' + ' at async Job.job (file:///mnt/Disk1/TRSS-Yunzai/lib/plugins/loader.js:516:9)', [message]: "Cannot read properties of null (reading 'join')" }

配置文件你是不是删了示例（）
你更新一下吧

**Comment by onlyzqy** [comment]
> > [23:48:18.484][ERRO][yuki插件---微博动态推送定时任务(*/5 * * * *)] TypeError: Cannot read properties of null (reading 'join') at WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:144:63) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async WeiboTask.pushDynamicMessages (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:111:29) at async WeiboTask.runTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:25:9) at async YukiWeibo.newPushTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/apps/weibo.js:60:9) at async Job.job (file:///mnt/Disk1/TRSS-Yunzai/lib/plugins/loader.js:516:9) { [stack]: "TypeError: Cannot read properties of null (reading 'join')\n" + ' at WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:144:63)\n' + ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' + ' at async WeiboTask.pushDynamicMessages (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:111:29)\n' + ' at async WeiboTask.runTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:25:9)\n' + ' at async YukiWeibo.newPushTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/apps/weibo.js:60:9)\n' + ' at async Job.job (file:///mnt/Disk1/TRSS-Yunzai/lib/plugins/loader.js:516:9)', [message]: "Cannot read properties of null (reading 'join')" }
> 
> 配置文件你是不是删了示例（） 你更新一下吧

发送消息错误 [ { type: 'image', file: <Buffer >, name: undefined }, [length]: 1 ] Error: request "/channels/633551994/messages" error with code(40083002): 图片转存失败, 原始图片上传失败
    at /mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:74:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Axios.request (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/axios@1.7.9/node_modules/axios/dist/node/axios.cjs:4247:14)
    at async Sender.sendMsg (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:235:34)
    at async Bot.sendGuildMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/bot.js:523:24)
    at async sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:691:19)
    at async QQBotAdapter.sendGMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:704:9)
    at async WeiboTask.sendMessage (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:295:13)
    at async WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:174:17)
    at async WeiboTask.pushDynamicMessages (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:111:29)
    at Axios.request (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/axios@1.7.9/node_modules/axios/dist/node/axios.cjs:4252:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Sender.sendMsg (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:235:34)
    at async Bot.sendGuildMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/bot.js:523:24)
    at async sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:691:19)
    at async QQBotAdapter.sendGMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:704:9)
    at async WeiboTask.sendMessage (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:295:13)
    at async WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:174:17)
    at async WeiboTask.pushDynamicMessages (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:111:29)
    at async WeiboTask.runTask (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:25:9) {
  [stack]: 'Error: request "/channels/633551994/messages" error with code(40083002): 图片转存失败, 原始图片上传失败\n' +
    '    at /mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:74:25\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Axios.request (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/axios@1.7.9/node_modules/axios/dist/node/axios.cjs:4247:14)\n' +
    '    at async Sender.sendMsg (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:235:34)\n' +
    '    at async Bot.sendGuildMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/bot.js:523:24)\n' +
    '    at async sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:691:19)\n' +
    '    at async QQBotAdapter.sendGMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:704:9)\n' +
    '    at async WeiboTask.sendMessage (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.'... 1437 more characters,
  [message]: 'request "/channels/633551994/messages" error with code(40083002): 图片转存失败, 原始图片上传失败'
}


[23:46:11.906][ERRO][2854212128] 发送消息错误 [
  {
    type: 'image',
    file: <Buffer 52 49 46 46 3a ab 01 00 57 45 42 50 56 50 38 58 0a 00 00 00 20 00 00 00 3b 03 00 22 04 00 49 43 43 50 c8 01 00 00 00 00 01 c8 00 00 00 00 04 30 00 00 ... 109328 more bytes>,
    name: undefined
  },
  [length]: 1
] Error: request "/v2/groups/746438576/files" error with code(11255): invalid request
    at /mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:74:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Axios.request (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/axios@1.7.9/node_modules/axios/dist/node/axios.cjs:4247:14)
    at async Bot.uploadMedia (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:124:34)
    at async Sender.processMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:173:58)
    at async Sender.sendMsg (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:230:9)
    at async Bot.sendGroupMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/bot.js:431:24)
    at async sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:571:19)
    at async QQBotAdapter.sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:594:7)
    at async BiliTask.sendMessage (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/bilibili/bilibili.main.task.js:328:13)
    at Axios.request (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/axios@1.7.9/node_modules/axios/dist/node/axios.cjs:4252:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bot.uploadMedia (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:124:34)
    at async Sender.processMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:173:58)
    at async Sender.sendMsg (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:230:9)
    at async Bot.sendGroupMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/bot.js:431:24)
    at async sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:571:19)
    at async QQBotAdapter.sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:594:7)
    at async BiliTask.sendMessage (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/bilibili/bilibili.main.task.js:328:13)
    at async BiliTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/bilibili/bilibili.main.task.js:207:17) {
  [stack]: 'Error: request "/v2/groups/746438576/files" error with code(11255): invalid request\n' +
    '    at /mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:74:25\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Axios.request (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/axios@1.7.9/node_modules/axios/dist/node/axios.cjs:4247:14)\n' +
    '    at async Bot.uploadMedia (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:124:34)\n' +
    '    at async Sender.processMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:173:58)\n' +
    '    at async Sender.sendMsg (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:230:9)\n' +
    '    at async Bot.sendGroupMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/bot.js:431:24)\n' +
    '    at async s'... 1545 more characters,
  [message]: 'request "/v2/groups/746438576/files" error with code(11255): invalid request'
}

更新之后i出现了这两种错误情况

**Comment by snowtafir** [comment]
> > > [23:48:18.484][ERRO][yuki插件---微博动态推送定时任务(*/5 * * * *)] TypeError: Cannot read properties of null (reading 'join') at WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:144:63) at ....
> > 
> > 
> > 配置文件你是不是删了示例（） 你更新一下吧
> 
> 发送消息错误 [ { type: 'image', file: , name: undefined }, [length]: 1 ] Error: request "/channels/633551994/messages" error with code(40083002): 图片转存失败, 原始图片上传失败 at /mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/....
> 
> 更新之后i出现了这两种错误情况

自己看：https://gitee.com/snowtafir/xianxin-plugin/issues/IAF37Q
就算是频道也需要设置主动推送权限

**Comment by onlyzqy** [comment]
> > > > [23:48:18.484][ERRO][yuki插件---微博动态推送定时任务(*/5 * * * *)] TypeError: Cannot read properties of null (reading 'join') at WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:144:63) at ....
> > > 
> > > 
> > > 配置文件你是不是删了示例（） 你更新一下吧
> > 
> > 
> > 发送消息错误 [ { type: 'image', file: , name: undefined }, [length]: 1 ] Error: request "/channels/633551994/messages" error with code(40083002): 图片转存失败, 原始图片上传失败 at /mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/....
> > 更新之后i出现了这两种错误情况
> 
> 自己看：https://gitee.com/snowtafir/xianxin-plugin/issues/IAF37Q 就算是频道也需要设置主动推送权限

[10:03:28.955][ERRO][2854212128] 发送消息错误 [
  {
    type: 'image',
    file: <Buffer 52 49 46 46 4e 4b 02 00 57 45 42 50 56 50 38 58 0a 00 00 00 20 00 00 00 3b 03 00 08 05 00 49 43 43 50 c8 01 00 00 00 00 01 c8 00 00 00 00 04 30 00 00 ... 150308 more bytes>,
    name: undefined
  },
  [length]: 1
] Error: request "/v2/groups/746438576/files" error with code(11255): invalid request
    at /mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:74:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Axios.request (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/axios@1.7.9/node_modules/axios/dist/node/axios.cjs:4247:14)
    at async Bot.uploadMedia (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:124:34)
    at async Sender.processMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:173:58)
    at async Sender.sendMsg (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:230:9)
    at async Bot.sendGroupMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/bot.js:431:24)
    at async sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:571:19)
    at async QQBotAdapter.sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:592:9)
    at async WeiboTask.sendMessage (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:295:13)
    at Axios.request (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/axios@1.7.9/node_modules/axios/dist/node/axios.cjs:4252:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bot.uploadMedia (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:124:34)
    at async Sender.processMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:173:58)
    at async Sender.sendMsg (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:230:9)
    at async Bot.sendGroupMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/bot.js:431:24)
    at async sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:571:19)
    at async QQBotAdapter.sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:592:9)
    at async WeiboTask.sendMessage (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:295:13)
    at async WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:174:17) {
  [stack]: 'Error: request "/v2/groups/746438576/files" error with code(11255): invalid request\n' +
    '    at /mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:74:25\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Axios.request (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/axios@1.7.9/node_modules/axios/dist/node/axios.cjs:4247:14)\n' +
    '    at async Bot.uploadMedia (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:124:34)\n' +
    '    at async Sender.processMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:173:58)\n' +
    '    at async Sender.sendMsg (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:230:9)\n' +
    '    at async Bot.sendGroupMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/bot.js:431:24)\n' +
    '    at async s'... 1515 more characters,
  [message]: 'request "/v2/groups/746438576/files" error with code(11255): invalid request'
}

私聊可以推送成功，但是群就发送错误

**Comment by snowtafir** [comment]
> > > > > [23:48:18.484][ERRO][yuki插件---微博动态推送定时任务(*/5 * * * *)] TypeError: Cannot read properties of null (reading 'join') at WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:144:63) at ....
> > > > 
> > > > 
> > > > 配置文件你是不是删了示例（） 你更新一下吧
> > > 
> > > 
> > > 发送消息错误 [ { type: 'image', file: , name: undefined }, [length]: 1 ] Error: request "/channels/633551994/messages" error with code(40083002): 图片转存失败, 原始图片上传失败 at /mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/....
> > > 更新之后i出现了这两种错误情况
> > 
> > 
> > 自己看：https://gitee.com/snowtafir/xianxin-plugin/issues/IAF37Q 就算是频道也需要设置主动推送权限
> 
> [10:03:28.955][ERRO][2854212128] 发送消息错误 [ { type: 'image', file: <Buffer 52 49 46 46 4e 4b 02 00 57 45 42 50 56 50 38 58 0a 00 00 00 20 00 00 00 3b 03 00 08 05 00 49 43 43 50 c8 01 00 00 00 00 01 c8 00 00 00 00 04 30 00 00 ... 150308 more bytes>, name: undefined }, [length]: 1 ] Error: request "/v2/groups/746438576/files" error with code(11255): invalid request at /mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:74:25 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Axios.request (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/axios@1.7.9/node_modules/axios/dist/node/axios.cjs:4247:14) at async Bot.uploadMedia (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:124:34) at async Sender.processMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:173:58) at async Sender.sendMsg (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:230:9) at async Bot.sendGroupMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/bot.js:431:24) at async sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:571:19) at async QQBotAdapter.sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:592:9) at async WeiboTask.sendMessage (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:295:13) at Axios.request (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/axios@1.7.9/node_modules/axios/dist/node/axios.cjs:4252:41) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Bot.uploadMedia (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:124:34) at async Sender.processMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:173:58) at async Sender.sendMsg (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:230:9) at async Bot.sendGroupMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/bot.js:431:24) at async sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:571:19) at async QQBotAdapter.sendMsg (file:///mnt/Disk1/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:592:9) at async WeiboTask.sendMessage (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:295:13) at async WeiboTask.sendDynamic (file:///mnt/Disk1/TRSS-Yunzai/plugins/yuki-plugin/models/weibo/weibo.task.js:174:17) { [stack]: 'Error: request "/v2/groups/746438576/files" error with code(11255): invalid request\n' + ' at /mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:74:25\n' + ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' + ' at async Axios.request (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/axios@1.7.9/node_modules/axios/dist/node/axios.cjs:4247:14)\n' + ' at async Bot.uploadMedia (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/qqBot.js:124:34)\n' + ' at async Sender.processMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:173:58)\n' + ' at async Sender.sendMsg (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/entries/sender.js:230:9)\n' + ' at async Bot.sendGroupMessage (/mnt/Disk1/TRSS-Yunzai/node_modules/.pnpm/qq-group-bot@1.1.0/node_modules/qq-group-bot/lib/bot.js:431:24)\n' + ' at async s'... 1515 more characters, [message]: 'request "/v2/groups/746438576/files" error with code(11255): invalid request' }
> 
> 私聊可以推送成功，但是群就发送错误

就问你是不是官方群bot吧（），如果是，那就不奇怪，主动消息（官方限制4条/月）
