### ISSUE TITLE
TRSS-Yunzai 无法发送消息

### ISSUE THREAD

**Issue by yuuki-nya** [snowtafir/yuki-plugin#15]
TRSS-Yunzai 3.1.3 https://github.com/TimeRainStarSky/Yunzai/commit/e7a7aab3c7b4ac77be941210d01576e178d0404d
yuki-plugin https://github.com/snowtafir/yuki-plugin/commit/8172f17de7739f636afb4e8b694d9f3a5495fcfd
发送任何图片相关的就会报错
```
[puppeteer] err TargetCloseError: Protocol error (Target.setDiscoverTargets): Target closed

    at CallbackRegistry.clear (file:///app/node_modules/.pnpm/puppeteer-core@22.3.0_encoding@0.1.13/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:72:36)

    at #onClose (file:///app/node_modules/.pnpm/puppeteer-core@22.3.0_encoding@0.1.13/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:152:25)

    at WebSocket.<anonymous> (file:///app/node_modules/.pnpm/puppeteer-core@22.3.0_encoding@0.1.13/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:41:30)

    at callListener (/app/node_modules/.pnpm/ws@8.16.0/node_modules/ws/lib/event-target.js:290:14)

    at WebSocket.onClose (/app/node_modules/.pnpm/ws@8.16.0/node_modules/ws/lib/event-target.js:220:9)

    at WebSocket.emit (node:events:518:28)

    at WebSocket.emitClose (/app/node_modules/.pnpm/ws@8.16.0/node_modules/ws/lib/websocket.js:265:10)

    at Socket.socketOnClose (/app/node_modules/.pnpm/ws@8.16.0/node_modules/ws/lib/websocket.js:1289:15)

    at Socket.emit (node:events:518:28)

    at TCP.<anonymous> (node:net:343:12) {

  cause: ProtocolError

      at <instance_members_initializer> (file:///app/node_modules/.pnpm/puppeteer-core@22.3.0_encoding@0.1.13/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:92:14)

      at new Callback (file:///app/node_modules/.pnpm/puppeteer-core@22.3.0_encoding@0.1.13/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:96:16)

      at CallbackRegistry.create (file:///app/node_modules/.pnpm/puppeteer-core@22.3.0_encoding@0.1.13/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)

      at Connection._rawSend (file:///app/node_modules/.pnpm/puppeteer-core@22.3.0_encoding@0.1.13/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:77:26)

      at Connection.send (file:///app/node_modules/.pnpm/puppeteer-core@22.3.0_encoding@0.1.13/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:71:21)

      at ChromeTargetManager.initialize (file:///app/node_modules/.pnpm/puppeteer-core@22.3.0_encoding@0.1.13/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ChromeTargetManager.js:83:32)

      at CdpBrowser._attach (file:///app/node_modules/.pnpm/puppeteer-core@22.3.0_encoding@0.1.13/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:67:35)

      at CdpBrowser._create (file:///app/node_modules/.pnpm/puppeteer-core@22.3.0_encoding@0.1.13/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:20:23)

      at ChromeLauncher.launch (file:///app/node_modules/.pnpm/puppeteer-core@22.3.0_encoding@0.1.13/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:107:48)

      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

}
```
尝试根据 https://github.com/snowtafir/yuki-plugin/issues/4 把 puppeteer 降级为 22.13.1 也无法解决

**Comment by yuuki-nya** [comment]
把 trss-yunzai 和 yuki-plugin 的 puppeteer 指定为 22.13.1 
```
[puppeteer] err TargetCloseError: Protocol error (Target.setDiscoverTargets): Target closed

    at CallbackRegistry.clear (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:69:36)

    at #onClose (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:161:25)

    at WebSocket.<anonymous> (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:43:30)

    at callListener (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/event-target.js:290:14)

    at WebSocket.onClose (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/event-target.js:220:9)

    at WebSocket.emit (node:events:518:28)

    at WebSocket.emitClose (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/websocket.js:272:10)

    at Socket.socketOnClose (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/websocket.js:1341:15)

    at Socket.emit (node:events:518:28)

    at TCP.<anonymous> (node:net:343:12) {

  cause: ProtocolError

      at <instance_members_initializer> (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)

      at new Callback (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)

      at CallbackRegistry.create (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)

      at Connection._rawSend (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:86:26)

      at Connection.send (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:77:21)

      at ChromeTargetManager.initialize (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ChromeTargetManager.js:88:32)

      at CdpBrowser._attach (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:69:35)

      at CdpBrowser._create (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:24:23)

      at ChromeLauncher.launch (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:114:48)

      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

}
```

**Comment by snowtafir** [comment]
> 把 trss-yunzai 和 yuki-plugin 的 puppeteer 指定为 22.13.1
> 
> ```
> [puppeteer] err TargetCloseError: Protocol error (Target.setDiscoverTargets): Target closed
> 
>     at CallbackRegistry.clear (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:69:36)
> 
>     at #onClose (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:161:25)
> 
>     at WebSocket.<anonymous> (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:43:30)
> 
>     at callListener (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/event-target.js:290:14)
> 
>     at WebSocket.onClose (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/event-target.js:220:9)
> 
>     at WebSocket.emit (node:events:518:28)
> 
>     at WebSocket.emitClose (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/websocket.js:272:10)
> 
>     at Socket.socketOnClose (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/websocket.js:1341:15)
> 
>     at Socket.emit (node:events:518:28)
> 
>     at TCP.<anonymous> (node:net:343:12) {
> 
>   cause: ProtocolError
> 
>       at <instance_members_initializer> (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)
> 
>       at new Callback (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)
> 
>       at CallbackRegistry.create (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
> 
>       at Connection._rawSend (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:86:26)
> 
>       at Connection.send (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:77:21)
> 
>       at ChromeTargetManager.initialize (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ChromeTargetManager.js:88:32)
> 
>       at CdpBrowser._attach (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:69:35)
> 
>       at CdpBrowser._create (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:24:23)
> 
>       at ChromeLauncher.launch (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:114:48)
> 
>       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
> 
> }
> ```

看仓库主页运行环境要求。不支持Edge浏览器

**Comment by yuuki-nya** [comment]
> > 把 trss-yunzai 和 yuki-plugin 的 puppeteer 指定为 22.13.1
> > ```
> > [puppeteer] err TargetCloseError: Protocol error (Target.setDiscoverTargets): Target closed
> > 
> >     at CallbackRegistry.clear (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:69:36)
> > 
> >     at #onClose (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:161:25)
> > 
> >     at WebSocket.<anonymous> (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:43:30)
> > 
> >     at callListener (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/event-target.js:290:14)
> > 
> >     at WebSocket.onClose (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/event-target.js:220:9)
> > 
> >     at WebSocket.emit (node:events:518:28)
> > 
> >     at WebSocket.emitClose (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/websocket.js:272:10)
> > 
> >     at Socket.socketOnClose (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/websocket.js:1341:15)
> > 
> >     at Socket.emit (node:events:518:28)
> > 
> >     at TCP.<anonymous> (node:net:343:12) {
> > 
> >   cause: ProtocolError
> > 
> >       at <instance_members_initializer> (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)
> > 
> >       at new Callback (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)
> > 
> >       at CallbackRegistry.create (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
> > 
> >       at Connection._rawSend (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:86:26)
> > 
> >       at Connection.send (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:77:21)
> > 
> >       at ChromeTargetManager.initialize (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ChromeTargetManager.js:88:32)
> > 
> >       at CdpBrowser._attach (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:69:35)
> > 
> >       at CdpBrowser._create (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:24:23)
> > 
> >       at ChromeLauncher.launch (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:114:48)
> > 
> >       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
> > 
> > }
> > ```
> 
> 看仓库主页运行环境要求。不支持Edge浏览器

不是 edge ，是 node 22.12.0 LTS 的官方 docker 镜像
```
/app $ chromium-browser --version
Chromium 131.0.6778.85 Alpine Linux
```
大概是yuki某次更新后就不行了，还没找到哪里不兼容

**Comment by snowtafir** [comment]
> > > 把 trss-yunzai 和 yuki-plugin 的 puppeteer 指定为 22.13.1
> > > ```
> > > [puppeteer] err TargetCloseError: Protocol error (Target.setDiscoverTargets): Target closed
> > > 
> > >     at CallbackRegistry.clear (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:69:36)
> > > 
> > >     at #onClose (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:161:25)
> > > 
> > >     at WebSocket.<anonymous> (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:43:30)
> > > 
> > >     at callListener (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/event-target.js:290:14)
> > > 
> > >     at WebSocket.onClose (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/event-target.js:220:9)
> > > 
> > >     at WebSocket.emit (node:events:518:28)
> > > 
> > >     at WebSocket.emitClose (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/websocket.js:272:10)
> > > 
> > >     at Socket.socketOnClose (/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/websocket.js:1341:15)
> > > 
> > >     at Socket.emit (node:events:518:28)
> > > 
> > >     at TCP.<anonymous> (node:net:343:12) {
> > > 
> > >   cause: ProtocolError
> > > 
> > >       at <instance_members_initializer> (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)
> > > 
> > >       at new Callback (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)
> > > 
> > >       at CallbackRegistry.create (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
> > > 
> > >       at Connection._rawSend (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:86:26)
> > > 
> > >       at Connection.send (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:77:21)
> > > 
> > >       at ChromeTargetManager.initialize (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ChromeTargetManager.js:88:32)
> > > 
> > >       at CdpBrowser._attach (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:69:35)
> > > 
> > >       at CdpBrowser._create (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:24:23)
> > > 
> > >       at ChromeLauncher.launch (file:///app/node_modules/.pnpm/puppeteer-core@22.13.1/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:114:48)
> > > 
> > >       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
> > > 
> > > }
> > > ```
> > 
> > 
> > 看仓库主页运行环境要求。不支持Edge浏览器
> 
> 不是 edge ，是 node 22.12.0 LTS 的官方 docker 镜像
> 
> ```
> /app $ chromium-browser --version
> Chromium 131.0.6778.85 Alpine Linux
> ```
> 
> 大概是yuki某次更新后就不行了，还没找到哪里不兼容

把puppeteer更新到最新看看。。

**Comment by yuuki-nya** [comment]
https://github.com/snowtafir/yuki-plugin/blob/main3/package.json

23.11.1 应该是最新的了，我新装个载试试

**Comment by yuuki-nya** [comment]
把docker镜像换成 node:22.12.0-bookworm 就可以了

**Comment by caiweilv** [comment]
一样的问题 还存在 更新之后就不行 尝试更新node chrome puppeteer全无效
