### ISSUE TITLE
菜单、扫码功能均无法使用

### ISSUE THREAD

**Issue by Ray-lea** [snowtafir/yuki-plugin#2]
环境：trss-yunzai+Napcat
扫码返回：
```
[20:37:46.871][INFO][553855023, 叱咤月海鱼鱼猫(2XXXX7)][#扫码B站登录][yuki-plugin-bilibili(scanBiliLogin)][开始处理]
[20:37:49.428][INFO][TRSSYz] [puppeteer] success
[20:37:49.496][MARK][TRSSYz] [图片生成][yuki-plugin][1次] 34.11kb 68ms
[20:37:49.542][INFO][32XXXX9 => 5XXXX3] 发送群消息：[{"type":"text","data":{"text":"请在3分钟内扫码以完成B站登陆绑定"}}]
[20:37:49.550][INFO][3XXXX9 => 5XXXX3] 发送群消息：[{"type":"image","data":{"file":"{\"0\":137,\"1\":80,:179,\"878\":154... 452101 more characters
[20:37:51.687][MARK][TRSSYz] yuki-yuki插件：扫码B站登录：未扫码，轮询中...
[20:37:51.869][ERRO][3XXXX] 发送消息错误 [
  {
    type: 'image',
    file: Uint8Array(34928) [
                       137,                     80,              78,                  71,
                       253,                     38,              89,                 106,
      ... 34828 more items, [BYTES_PER_ELEMENT]: 1, [length]: 34928, [byteLength]: 34928,
           [byteOffset]: 0,
      [buffer]: ArrayBuffer { byteLength: 34928 }
    ],
    name: undefined
  },
  [length]: 1
] Error
    at OneBotv11Adapter.sendApi (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:21:19)
    at Object.sendApi (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:709:41)
    at file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:113:23
    at OneBotv11Adapter.sendMsg (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:91:22)
    at async e.reply (file:///C:/Users/Administrator/Desktop/Yunzai/lib/plugins/loader.js:480:15) {
  [stack]: 'Error\n' +
    '    at OneBotv11Adapter.sendApi (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:21:19)\n' +
    '    at Object.sendApi (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:709:41)\n' +
    '    at file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:113:23\n' +
    '    at OneBotv11Adapter.sendMsg (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:91:22)\n' +
    '    at async e.reply (file:///C:/Users/Administrator/Desktop/Yunzai/lib/plugins/loader.js:480:15)',
  action: 'send_msg',
  params: {
    group_id: XXXX,
    message: [
      {
        type: 'image',
        data: {
          type: undefined,
          file: '{"0":137,"1":80,"2":78,"3":71,"4":13,"5":106,"119":98'... 391202 more characters,
          name: undefined
        }
      },
      [length]: 1
    ]
  },
  echo: '01J539GGVG2ABE9PT4WXZ930X6',
  error: {
    status: 'failed',
    retcode: 1200,
    data: null,
    message: 'Error: 文件下载失败uri {"0":137,"1":80,"2":78,"3":71,"4":13,"116":38,"117":49,"'... 784357 more characters,
    wording: 'Error: 文件下载失败uri {"0":137,"1":80,"2":78,"3":71,"4":13,"5":10,"6":26,"117":49,"'... 784357 more characters,
    echo: '01J539GGVG2ABE9PT4WXZ930X6',
    raw: '{"status":"failed","retcode":1200,"data":null,"message":"Error: 文件下载失败uri {\\"0\\":137,\\":174,\\"90\\":70,\\"91\\":241,\\"9'... 1849260 more characters
  }
}
[20:37:54.267][MARK][TRSSYz] yuki-yuki插件：扫码B站登录：未扫码，轮询中...
[20:37:56.384][MARK][TRSSYz] yuki-yuki插件：扫码B站登录：未扫码，轮询中..
```
 `#yuki帮助`返回（`yuki帮助`和`优纪帮助`无返回内容）：
```
[20:40:57.782][INFO][3XXXX9 <= 5XXXX3, 26XXXX97] 群消息：[『放逐之城贴吧官方群』『Ⅱ』『流萤』『蝴蝶直辖区』, 叱咤月海鱼鱼猫] #yuki帮助
[20:40:58.346][INFO][5XXXX3, 叱咤月海鱼鱼猫(2XXXX7)][#yuki帮助][yuki-help(yukiHelp)][开始处理]
[20:40:59.887][INFO][TRSSYz] [puppeteer] success
[20:41:01.022][MARK][TRSSYz] [图片生成][yukiHelp][1次] 1153.32kb 1135ms
[20:41:02.479][INFO][3214695699 => 553855023] 发送群消息：[{"type":"image","data":{"file":"{\"0\":137,\"1\":80，、,\"870\":1,\"871\":239,... 17266451 more characters
[20:41:11.621][ERRO][3XXXX9] 发送消息错误 [
  {
    type: 'image',
    file: Uint8Array(1181001) [
                         137,                     80,                78,                    71,
                          13,                     10,                26,                    10,
      ... 1180901 more items, [BYTES_PER_ELEMENT]: 1, [length]: 1181001, [byteLength]: 1181001,
             [byteOffset]: 0,
      [buffer]: ArrayBuffer { byteLength: 1181001 }
    ],
    name: undefined
  },
  [length]: 1
] Error
    at OneBotv11Adapter.sendApi (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:21:19)
    at Object.sendApi (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:709:41)
    at file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:113:23
    at OneBotv11Adapter.sendMsg (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:91:22)
    at async e.reply (file:///C:/Users/Administrator/Desktop/Yunzai/lib/plugins/loader.js:480:15)
    at async YukiHelp.yukiHelp (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/yuki-plugin/apps/help.js:48:9)
    at async PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Yunzai/lib/plugins/loader.js:264:41) {
  [stack]: 'Error\n' +
    '    at OneBotv11Adapter.sendApi (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:21:19)\n' +
    '    at Object.sendApi (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:709:41)\n' +
    '    at file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:113:23\n' +
    '    at OneBotv11Adapter.sendMsg (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:91:22)\n' +
    '    at async e.reply (file:///C:/Users/Administrator/Desktop/Yunzai/lib/plugins/loader.js:480:15)\n' +
    '    at async YukiHelp.yukiHelp (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/yuki-plugin/apps/help.js:48:9)\n' +
    '    at async PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Yunzai/lib/plugins/loader.js:264:41)',
  action: 'send_msg',
  params: {
    group_id: 5XXXX3,
    message: [
      {
        type: 'image',
        data: {
          type: undefined,
          file: '{"0":137,"1":80,"2":78,"3":71,"4":13,"5":10,"6":26,"117":109,"118":102,"119":2'... 14913406 more characters,
          name: undefined
        }
      },
      [length]: 1
    ]
  },
  echo: '01J539PD8KFB86R86BMKS6DAB5',
  error: {
    status: 'failed',
    retcode: 1200,
    data: null,
    message: 'Error: 文件下载失败uri {"0":137,"1":80,"2":78,"3":71,"4":13,"5":10,"116":169,"117":109,'... 29828765 more characters,
    wording: 'Error: 文件下载失败uri {"0":137,"1":80,"2":78,"3":71,"4":13,"5":10,"6""117":109,'... 29828765 more characters,
    echo: '01J539PD8KFB86R86BMKS6DAB5',
    raw: '{"status":"failed","retcode":1200,"data":null,"message":"Error: 文件下载失败uri {\\"0\\":137,\\"1\\":80,\\"2\\":78,\\"3\\":71,\\"4\\":13,\\"5\\":10,\\"6\\":26,\\"7\\":1
30,\\'... 69106660 more characters
  }
}
[20:41:11.644][MARK][553855023, 叱咤月海鱼鱼猫(2XXXX7)][#yuki帮助][yuki-help(yukiHelp)][完成13.298秒]

```

**Comment by snowtafir** [comment]
> 环境：trss-yunzai+Napcat 扫码返回：
> 
> ```
> [20:37:46.871][INFO][553855023, 叱咤月海鱼鱼猫(2XXXX7)][#扫码B站登录][yuki-plugin-bilibili(scanBiliLogin)][开始处理]
> [20:37:49.428][INFO][TRSSYz] [puppeteer] success
> [20:37:49.496][MARK][TRSSYz] [图片生成][yuki-plugin][1次] 34.11kb 68ms
> [20:37:49.542][INFO][32XXXX9 => 5XXXX3] 发送群消息：[{"type":"text","data":{"text":"请在3分钟内扫码以完成B站登陆绑定"}}]
> [20:37:49.550][INFO][3XXXX9 => 5XXXX3] 发送群消息：[{"type":"image","data":{"file":"{\"0\":137,\"1\":80,:179,\"878\":154... 
> ```
新版Napcat的问题，新版Napcat+trss炸了，降级Napcat试试。可以关注Napcat官方群组获取最新情况。

**Comment by Ray-lea** [comment]
> > 环境：trss-yunzai+Napcat 扫码返回：
> > ```
> > [20:37:46.871][INFO][553855023, 叱咤月海鱼鱼猫(2XXXX7)][#扫码B站登录][yuki-plugin-bilibili(scanBiliLogin)][开始处理]
> > [20:37:49.428][INFO][TRSSYz] [puppeteer] success
> > [20:37:49.496][MARK][TRSSYz] [图片生成][yuki-plugin][1次] 34.11kb 68ms
> > [20:37:49.542][INFO][32XXXX9 => 5XXXX3] 发送群消息：[{"type":"text","data":{"text":"请在3分钟内扫码以完成B站登陆绑定"}}]
> > [20:37:49.550][INFO][3XXXX9 => 5XXXX3] 发送群消息：[{"type":"image","data":{"file":"{\"0\":137,\"1\":80,:179,\"878\":154... 
> > ```
> 
> 新版Napcat的问题，新版Napcat+trss炸了，降级Napcat试试。可以关注Napcat官方群组获取最新情况。

好的
